name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: false  # disable cache for debugging

    - name: Check Node and npm versions
      run: |
        node -v
        npm -v

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Remove node_modules folder
      run: rm -rf node_modules

    - run: npm ci

    - run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
